const S = {
  appSettings: {},
  appCriteria: null,
  deviceStore: {},
  meshData: [],
  l2tpData: [],
  clientsData: [],
  /** @type {null | Array<{ mac: string, label?: string, vlan?: number }>} null = noch nicht von /api/nac geladen */
  nacMacAllowlistCache: null,
  meshFilter: 'all',
  clientsFilter: 'all',
  l2tpFilter: 'all',
  devFilter: 'all',
  devLocFilter: 'all',
  meshLocFilter: 'all',
  l2tpLocFilter: 'all',
  topoLocFilter: 'all',
  /** Netzwerkplan: lx-ap / lcos-ap aus dem Graphen ausblenden */
  topoHideAccessPoints: (() => {
    try { return localStorage.getItem('onsite_topo_hide_ap') === '1'; } catch (e) { return false; }
  })(),
  /** Netzwerkplan: nicht verwaltete Knoten (LLDP-„Geist“, L2TP ohne Gerät) ausblenden */
  topoHideUnmanaged: (() => {
    try { return localStorage.getItem('onsite_topo_hide_unmanaged') === '1'; } catch (e) { return false; }
  })(),
  meshSort: { col: null, dir: 1 },
  l2tpSort: { col: null, dir: 1 },
  roamSort: { col: null, dir: 1 },
  devSort: { col: 'ip', dir: 1 },
  scanResults: [],
  scanAbort: null,
  scanFoundCnt: 0,
  dashLastStatusCheck: null,
  dashLastDataSync: null,
  dashUptimeCache: {},
  stpStore: {},
  stpNodePos: (() => { try { return JSON.parse(localStorage.getItem('onsite_stp_pos')||'{}'); } catch(e) { return {}; } })(),
  stpEntries: [],
  stpEdgeData: [],
  stpScale: 1,
  stpTx: 0,
  stpTy: 0,
  stpDragNode: null,
  stpPan: null,
  stpWasDrag: false,
  STP_NW: 190,
  STP_NH: 96,
  ldLastResults: [],
  activityLog: [],
  ACTIVITY_LOG_MAX: 50,
  // SDN
  vlans: [],
  // Scanner
  rolloutScanAbort: null,
  // Topology
  topoNodes: {},
  topoEdges: [],
  topoLldpMap: {},
  topoRoot: '',
  topoDetailId: null,
  topoScale: 1,
  topoTx: 0,
  topoTy: 0,
  topoDragNode: null,
  topoPan: null,
  topoWasDrag: false,
  topoMode: 'default',
  topoTrafficEnabled: false,
  topoTrafficData: {},
  topoTrafficHistory: {},
  topoTrafficTimer: null,
  topoMacSearch: '',
  topoMacSearchResults: [],
  NODE_W: 190,
  NODE_H: 84,
  // WiFi Plan
  wpNodes: [],
  wpEdges: [],
  wpScale: 1,
  wpTx: 0,
  wpTy: 0,
  wpDragNode: null,
  wpPan: null,
  wpWasDrag: false,
  wpBandFilter: 'all',
  WP_NW: 170,
  WP_NH: 90,
  // Uptime tracking
  uptimeStats: {},
  // Auto-sync
  autoSyncTimer: null,
  autoSyncMinutes: 0,
};
export default S;
